# Generated by Django 3.0.8 on 2020-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
