# Generated by Django 3.0.8 on 2020-07-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tasklist_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['datetime']},
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='ogranization',
            new_name='organization',
        ),
    ]
